### PR TITLE
Directory structure refactoring

### PR DESCRIPTION
**Pull request by edward2018211**
Moved segmentation.py and ner.py into a service folder for better directory structure.

### CODE REVIEW

**Comment by pandevim** [comment]
Are you still working on this or is this PR complete?

**Comment by edward2018211** [comment]
Not finished quite yet.

**Comment by edward2018211** [comment]
One thing that I changed was that originally, the ```inference.py```, ```model.py```, and ```abc-news-date-text.csv``` were in a folder called ```topic_modelling``` in the root directory. I decided to delete that folder since I couldn't find an easy way to import the functions in the service folder since I had to go into the parent directory first, then import from service. Let me know if you guys have any suggestions for this, otherwise I think it might be fine to leave it like this.

**Comment by karkipra** [comment]
@edward2018211 what does the new directory structure look like? It's hard to tell from just from this PR.

**Comment by edward2018211** [comment]
@karkipra The main changes in directory structure was that I took all the helper functions from ```ner.py```, ```segmentation.py```, ```inference.py```,  and ```model.py``` and put those functions into the service folder. Inside the service folder, I organized the different helper functions into 4 separate files based on what they are used for.

**Pull request closed without merging**
